### ISSUE TITLE
Latest version causes flashes when it updates

### ISSUE THREAD

**Issue by DanClarke-io** [fewieden/MMM-ping#4]
Is there anyway in the latest version to prevent the content from disappearing and re-appearing each time a ping is run? I use this as a dashboard and it does become a bit distracting.

**Comment by fewieden** [comment]
@OverByThere I implemented a transition of 300ms like most modules do with https://docs.magicmirror.builders/development/core-module-file.html#this-updatedom-speed

**Comment by DanClarke-io** [comment]
Hi @fewieden, thanks for this. I've changed it to 0 for the time being and will see how it performs.

Thanks for the swift response!

Dan

**Comment by fewieden** [comment]
@OverByThere you have now also the possibility to define the `transitionTime` in the config.js directly in version 2.0.1
